# baseURL = 'http://example.org/' # Set in the GitHub Actions as a command line arg
languageCode = 'en-us'
title = 'Dhikr Hub'
enableGitInfo = true
enableRobotsTXT = true
######################
# Theme Theme Config
######################
theme = "hugo-book"
[params]
# light / dark
BookTheme = 'auto'

# path: static/<path-to-logo.png>
BookLogo = 'favicon.svg'

# path: static/<path-to-favicon>
BookFavicon = 'favicon.svg'

# In the left-handside display, show all the pages in the content/
BookSection = '*'

# Set source repository location.
# Used for 'Last Modified' and 'Edit this page' links.
BookRepo = 'https://github.com/adehad/dhikr-hub'

# Enable 'Edit this page' links for 'doc' page type.
# Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
# Path must point to the site directory.
BookEditPath = 'blob/HEAD/site'

# Enable Experimental Service Worker
BookServiceWorker = "precache" # precache caches all webpages

[markup.tableOfContents]
startLevel = 1

[taxonomies]
maqam = 'maqam'
# Default
# category = 'categories'
# series = 'series'
# tag = 'tags'
# Default End

# Mount data/qasida as static files for API access
# This makes JSON files available at /api/qasida/*.json
# Hugo watches these files and serves them during development
[module]
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "data/qasida"
    target = "static/api/qasida"
